(in-package #:day-12)

(defvar *input* "input/day12.txt")

(defun parse-command (command)
  (cons (ecase (char command 0)
          (#\N 'north)
          (#\S 'south)
          (#\E 'east)
          (#\W 'west)
          (#\L 'left)
          (#\R 'right)
          (#\F 'forward))
        (parse-integer (subseq command 1))))

(defun load-commands-from-file (file)
  (mapcar #'parse-command (read-lines file)))

(defun turn (heading direction amount)
  (unless (or (eq direction 'left) (eq direction 'right))
    (error (format nil "Invalid turn direction: ~a~%" direction)))
  (let* ((cardinals '(north east south west))
         (ticks (/ amount 90))
         (cur-index (position heading cardinals))
         (new-position (if (eq direction 'left)
                           (nth (mod (decf cur-index ticks) 4) cardinals)
                           (nth (mod (incf cur-index ticks) 4) cardinals))))
    new-position))

(defun part-1 ()
  (let ((pos (cons 0 0))
        (bearing 'east))
    (labels ((move (command)
               (ecase (car command)
                 (north (incf (cdr pos) (cdr command)))
                 (south (decf (cdr pos) (cdr command)))
                 (east (incf (car pos) (cdr command)))
                 (west (decf (car pos) (cdr command)))
                 (left (setf bearing (turn bearing 'left (cdr command))))
                 (right (setf bearing (turn bearing 'right (cdr command))))
                 (forward (move (cons bearing (cdr command)))))
      (dolist (cmd (load-commands-from-file *input*))
        (move cmd)))
    (+ (abs (car pos)) (abs (cdr pos)))))))


