(in-package #:day-8)

(defvar *input* "input/day8.txt")

(defun parse-instruction (instruction)
  (let* ((tokens (split " " instruction))
         (inst (first tokens))
         (val (parse-integer (second tokens))))
    (cond
      ((string= inst "acc") `(ACC . ,val))
      ((string= inst "nop") `(NOP . ,val))
      ((string= inst "jmp") `(JMP . ,val))
      (t (error (format nil "ILLEGAL INSTRUCTION: ~A~%" inst))))))


(defun load-program (file)
  (let ((lines (read-lines file)))
    (make-array (length lines) :initial-contents (mapcar #'parse-instruction lines))))

(defun find-loop (program)
  (do* ((code (if (stringp program)
                  (load-program program)
                  program))
        (acc 0)
        (ip 0 (incf ip inc))
        (inc 1 1)
        (hist '() (cons ip hist))
        (infinite-loop nil)
        (inst (aref code ip) (aref code ip)))
      ((or infinite-loop (>= (1+ ip) (length code))) (list infinite-loop acc))
    (case (car inst)
      (acc (incf acc (cdr inst)))
      (jmp (setf inc (cdr inst)))
      (nop nil))
    (if (member (+ ip inc) hist)
        (setf infinite-loop t))))

(defun part-1 ()
  (cadr (find-loop *input*)))

(defun jmp-nop-indices (program)
  (do ((index 0 (1+ index))
       (found nil))
      ((<= (length program) (1+ index)) found)
    (if (or (eq (car (aref program index)) 'JMP)
            (eq (car (aref program index)) 'NOP))
        (setf found (cons index found)))))

(defun flipped (program index)
  (let* ((copied (make-array (array-dimensions program) :initial-contents program))
         (inst (aref copied index)))
    (setf (aref copied index)
          (case (car inst)
            (jmp `(NOP . ,(cdr inst)))
            (nop `(JMP . ,(cdr inst)))
            (otherwise (error "invalid flip"))))
    copied))

(defun part-2 ()
  (let* ((program (load-program *input*))
         (indices (jmp-nop-indices program)))
    (dolist (i indices)
      (let* ((test (flipped program i))
             (result (find-loop test)))
        (unless (car result)
          (return-from part-2 (cadr result)))))))
